### ISSUE TITLE
missing rocket.ico file on APOD app

### ISSUE THREAD

**Issue by alejandroautalan** [lildinti/pygubu-examples#1]
Hello.
An error is shown when I click the "show full picture" button.  The rocket.ico file is missing.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "apodapp.py", line 105, in fullscreen_clicked
    top.iconbitmap('rocket.ico')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "rocket.ico" not defined
```

Saludos
Alejandro A.

**Comment by lildinti** [comment]
Removed Top.iconbitmap line as not relevant.
